const ATTACK_PATTERNS = {
  credential_harvesting:{keywords:["verify your account","confirm your password","login immediately","account suspended","click here to restore","validate your credentials","update your credentials","unauthorized access detected","verify your identity","account will be closed","account has been suspended","verify your email","confirm your identity","reset your password","account verification required","security check required","sign in to confirm"],title:"Credential Harvesting",what_they_want:"Your login credentials — username, password, and security questions",risk_level:"critical",advice:"Do not click any links. Open your browser and navigate directly to the official website by typing the URL manually."},
  ceo_fraud:{keywords:["urgent wire transfer","strictly confidential","do not tell anyone","need this done today","wire transfer","confidential transaction","transfer funds immediately","personal request from","executive request","keep this between us","act quickly on this","business transaction","transfer the amount","don't discuss this","between you and me","send the funds","make the payment today"],title:"CEO Fraud / BEC",what_they_want:"Company funds — a wire transfer to an attacker-controlled bank account",risk_level:"critical",advice:"Call the executive directly using a known, verified phone number. Never initiate wire transfers based solely on email instructions."},
  fake_invoice:{keywords:["payment overdue","attached invoice","bank transfer required","outstanding balance","invoice attached","payment due immediately","remittance required","overdue payment notice","settle your account","final notice","unpaid invoice","payment confirmation required","invoice number","billing statement enclosed","amount due","past due amount"],title:"Fake Invoice Scam",what_they_want:"A direct payment to the attacker's bank account disguised as a legitimate invoice",risk_level:"high",advice:"Verify any invoice through your official vendor portal or finance team. Call the vendor using a number from their official website."},
  bank_scam:{keywords:["card has been blocked","unusual activity detected","verify your identity now","net banking","account has been frozen","suspicious transaction on your account","banking security alert","transaction was declined","security verification required","blocked card","your bank account","one-time password","otp required","banking credentials","debit card details","credit card information required"],title:"Banking Scam",what_they_want:"Your banking credentials, card numbers, and one-time passwords (OTPs)",risk_level:"critical",advice:"Call your bank using the official number on the back of your card. Your bank will never ask for your OTP or full card number via email or SMS."},
  package_delivery:{keywords:["your package is held","delivery attempt failed","pay customs fee","reschedule your delivery","package is awaiting","delivery failed","shipping fee required","customs clearance fee","parcel is held","delivery notification","package cannot be delivered","redelivery fee","courier notification","your shipment requires","delivery address confirmation"],title:"Package Delivery Scam",what_they_want:"Credit card details under the pretense of paying a small fake delivery or customs fee",risk_level:"medium",advice:"Check delivery status directly on the official courier website. Legitimate couriers never request payment via email or SMS links."},
  crypto_scam:{keywords:["bitcoin investment","crypto opportunity","guaranteed returns","double your bitcoin","elon musk crypto","binance giveaway","deposit crypto","trading bot","passive income crypto","crypto wallet verification","blockchain verification required","nft giveaway","metamask support","trust wallet issue","seed phrase required","wallet recovery","crypto profit daily"],title:"Crypto Scam",what_they_want:"Cryptocurrency wallet access, seed phrases, or direct crypto transfers to attacker wallets",risk_level:"critical",advice:"Never share seed phrases or private keys with anyone. Legitimate crypto platforms never ask for wallet credentials. All 'guaranteed return' offers are scams."},
  romance_scam:{keywords:["i love you already","i feel connected to you","send me money","i am stuck abroad","military deployment","need money urgently","buy gift cards","western union","moneygram","wire me","my father is sick","medical emergency abroad","i want to meet you","investment together","business partner funds"],title:"Romance Scam",what_they_want:"Money via wire transfer, gift cards, or cryptocurrency, exploiting emotional trust built over time",risk_level:"critical",advice:"Never send money to someone you haven't met in person. Be skeptical of anyone asking for financial help online, even if the relationship feels genuine."},
  job_scam:{keywords:["work from home opportunity","earn 50000 daily","data entry job","no experience required","immediate joining bonus","advance payment required","training fee required","registration fee job","job guarantee","part time job online","typing job work","copy paste job","hr recruiter contacted you","selected for interview offer","job offer letter attached"],title:"Job Offer Scam",what_they_want:"Upfront registration/training fees, or personal documents like Aadhaar/PAN for identity theft",risk_level:"high",advice:"Legitimate employers never ask for upfront payment. Verify company identity on LinkedIn or official website. Never share personal ID documents without thorough verification."},
  tech_support:{keywords:["your computer is infected","call microsoft support","windows has detected","your license has expired","suspicious activity on your device","call this number immediately","technical support team","your ip has been flagged","remote access required","download this software","install this tool","your antivirus expired"],title:"Tech Support Scam",what_they_want:"Remote access to your computer and payment for fake support, exposing all your personal data",risk_level:"high",advice:"Microsoft/Apple/Google never proactively contact you about viruses. Close the browser immediately. Never call numbers shown in browser alerts or popups."},
  lottery_scam:{keywords:["you have won","congratulations winner","claim your prize","lottery winner selected","lucky winner","prize money transfer","claim before it expires","processing fee required","you have been selected randomly","lucky draw winner","prize bond winner","million dollar prize","sweepstakes winner"],title:"Lottery / Prize Scam",what_they_want:"Processing/release fees upfront, and your banking details to 'transfer the winnings'",risk_level:"high",advice:"You cannot win a lottery you never entered. Any 'prize' requiring upfront payment is always a scam. Block and report the sender immediately."}
};

const PLATFORM_PATTERNS = {
  whatsapp:{keywords:["forwarded many times","forward this message","send to all contacts","free recharge","free data offer","government free scheme","pm yojana","your whatsapp will expire","whatsapp gold","new whatsapp version","send to 10 friends","earn daily work from home","5000 daily","arrested if not forwarded","account blocked permanently","jio free data","airtel free recharge offer","bsnl free data"],title:"WhatsApp Scam",what_they_want:"Personal data, UPI money transfers, or spreading malware through your contact network",risk_level:"high",advice:"Do not forward suspicious messages. Verify any scheme on official government websites. Never send money via UPI to unverified contacts."},
  instagram:{keywords:["brand collaboration","paid promotion opportunity","free products to review","your account will be disabled","copyright infringement notice","verified badge offer","follower boost service","buy real followers","guaranteed investment returns","crypto giveaway instagram","limited collab offer","congratulations you have been selected","send advance payment for collab","shipping fee required for prize","dm us your address","we loved your content apply now"],title:"Instagram DM Scam",what_they_want:"Payment for fake collaborations, account credentials via fake violation notices, or investment fraud",risk_level:"high",advice:"Real brands reach out via official email, not DMs. Never pay upfront for collaborations. Report fake copyright notices through Instagram's official Help Center."},
  sms:{keywords:["your otp is","do not share otp","one time password","free msg:","txt stop to cancel","reply stop to opt out","your parcel is held","delivery failed reschedule","won a prize claim","selected for reward click","kyc update required urgently","sim will be blocked","income tax refund click","aadhaar linked with","pan card blocked update","upi blocked verify now"],title:"SMS Phishing (Smishing)",what_they_want:"OTPs, banking credentials, or card details via fake delivery, prize, or banking SMS alerts",risk_level:"critical",advice:"Banks NEVER ask for OTP via SMS link. Telecoms NEVER block SIM via SMS. Always verify by calling official numbers from the company's official website."}
};

const URGENCY_WORDS=["immediately","urgent","asap","right now","within 24 hours","within 48 hours","expires today","act now","limited time","final warning","last chance","time sensitive","respond now","do not delay","before it's too late","deadline","expiring soon","action required","must act","hours left"];
const THREAT_WORDS=["suspended","terminated","deleted","blocked","frozen","locked","compromised","hacked","breached","cancelled","deactivated","permanently closed","legal action","prosecuted","reported to authorities","arrest","penalty","fine imposed","account seized"];
const MANIP_WORDS=["click here","click the link","click below","follow this link","tap here","visit this link","download now","open attachment","view document","access here","confirm here","verify here","tap to confirm","scan qr","open the link"];

const SUSP_TLDS=['.xyz','.top','.click','.live','.online','.site','.tk','.ml','.ga','.cf','.gq','.pw','.cc','.ws'];
const URL_SHORT=['bit.ly','tinyurl.com','goo.gl','ow.ly','is.gd','t.me','cutt.ly','rebrand.ly','short.io','tiny.cc','buff.ly','t.ly','rb.gy'];
const LOOKALIKE=['paypal','amazon','google','microsoft','apple','facebook','instagram','netflix','hdfc','sbi','icici','axis','kotak','flipkart','phonepe','paytm','zomato','swiggy','ola','uber'];

const PLAT_CFG={
  email:{label:'Email',icon:'✉',color:'#38bdf8',cardClass:'pe',tabClass:'ae',btnClass:'',ph:'Paste a suspicious email here...\n\nInclude the full email body, subject, and any links for the most accurate analysis.'},
  whatsapp:{label:'WhatsApp',icon:'💬',color:'#25d366',cardClass:'pw',tabClass:'aw',btnClass:'bw',ph:'Paste a suspicious WhatsApp message here...\n\nForwarded messages, prize claims, free offer messages, or urgent requests.'},
  instagram:{label:'Instagram',icon:'📸',color:'#ec4899',cardClass:'pi',tabClass:'ai',btnClass:'bi',ph:'Paste a suspicious Instagram DM here...\n\nFake brand collabs, copyright notices, follower boost offers, or investment schemes.'},
  sms:{label:'SMS',icon:'📱',color:'#fb923c',cardClass:'ps',tabClass:'as',btnClass:'bs',ph:'Paste a suspicious SMS / text message here...\n\nBank alerts, OTP requests, delivery notifications, or prize claim messages.'},
  url:{label:'URL / Link',icon:'🔗',color:'#a78bfa',cardClass:'pu',tabClass:'au',btnClass:'bu',ph:'Paste a suspicious URL or any message containing links here...\n\nPhishDNA will scan all URLs for lookalike domains, shorteners, and suspicious patterns.'}
};

const PRESETS={
  email:[
    {label:'Bank Alert',text:`Dear Valued Customer,\n\nWe have detected unusual activity on your account. Your debit card has been temporarily blocked due to a suspicious transaction of $1,247.00 made from an unrecognized device.\n\nTo restore full access, you must verify your identity immediately by clicking the link below. Failure to verify within 24 hours will result in your account being permanently frozen.\n\nVerify your account now → http://secure-bank-verify.xyz/confirm\n\nThis is a time sensitive security alert. Do not share this message with anyone.\n\n— Security Team, National Bank`},
    {label:'CEO Fraud',text:`Hi,\n\nThis is urgent. I need you to process a wire transfer of $48,500 to a new vendor account today. This is strictly confidential — do not discuss with anyone in the office.\n\nI'm currently in a meeting and can't talk. Please make the payment today and I'll explain everything later. Keep this between us.\n\nThanks\nCEO`},
    {label:'Fake Invoice',text:`Dear Finance Team,\n\nPlease find attached the invoice #INV-2024-0892 for services rendered. The outstanding balance of $12,850 is now past due.\n\nThis is a final notice. Please process the bank transfer immediately to avoid late payment penalties.\n\nAmount Due: $12,850\nBank Transfer Required within 48 hours\n\nRegards\nAccounts Team`},
    {label:'Safe Email',text:`Hi team,\n\nJust a reminder that our weekly sync is scheduled for Thursday at 3pm. Please review the agenda document I shared earlier and come prepared with your project updates.\n\nLooking forward to seeing everyone!\n\nBest,\nSarah`}
  ],
  whatsapp:[
    {label:'Free Recharge',text:`🎉 CONGRATULATIONS!! You have been selected for FREE 84GB data and unlimited calling for 3 months! This is a special Jio/Airtel government scheme for loyal customers.\n\nForward this message to 10 friends and click the link to claim: http://free-data-offer.xyz/claim\n\nHurry! Offer expires in 2 hours. Share with all contacts! 🔥`},
    {label:'Chain Scam',text:`⚠️ WARNING: WhatsApp will expire tomorrow unless you forward this message to 20 contacts. WhatsApp Gold is now available — upgrade now to get new features.\n\nDo NOT ignore this message. You will be permanently blocked if you don't forward this to all your contacts within 24 hours.`},
    {label:'Job Scam',text:`Hi, I am from HR Team. We have a work from home opportunity for you. Earn 5000 daily doing simple data entry job. No experience required. Immediate joining. Just pay a small registration fee and get started today. WhatsApp me your Aadhaar card and bank account details.`}
  ],
  instagram:[
    {label:'Fake Collab',text:`Hey! 👋 We love your content and would like to offer you a brand collaboration. You will receive free products worth $500 plus a paid promotion fee.\n\nThis is a limited collab offer — only 5 spots available. To confirm, we need an advance payment for collab of $50 for shipping. DM us your address and payment details. Offer expires in 24 hours!`},
    {label:'Copyright Notice',text:`⚠️ IMPORTANT: Your account will be disabled within 24 hours due to copyright infringement notice. Verify your identity immediately.\n\nClick the link to submit your appeal: http://instagram-verify-account.top/appeal\n\nFailure to verify will result in permanent account deletion. Act now!`}
  ],
  sms:[
    {label:'Bank SMS',text:`SBI ALERT: Your account XX4521 is frozen due to suspicious activity. Your debit card has been blocked. KYC update required urgently. Click here: http://sbi-kyc-update.click/verify or account will be permanently closed within 24 hours.`},
    {label:'Delivery SMS',text:`FedEx: Your parcel is held at customs. Pay customs clearance fee of Rs.199 to release your package. Click to pay: http://fedex-delivery.xyz/pay Offer expires today. Reply STOP to opt out.`},
    {label:'OTP Scam',text:`Your OTP for SBI NetBanking is 847291. Do NOT share this one time password with anyone. Valid for 10 mins. If not requested, secure your account: http://sbi-secure.top/block`}
  ],
  url:[
    {label:'Suspicious Links',text:`Please verify your account at: http://paypa1-secure-verify.xyz/login?user=confirm\nAlso track your delivery at: http://192.168.1.45:8080/track\nOr visit: https://bit.ly/3xKmP9q for more details`},
    {label:'Lookalike Domains',text:`Your account has been suspended. Restore at: http://amazon-account-verify.top/restore\nUpdate payment at: http://paypal.secure-update.click/billing\nContact: http://microsoft-helpdesk.xyz/support`}
  ]
};

const RISK_CFG={
  danger:{color:'#f43f5e',dot:'#f43f5e'},
  warning:{color:'#fb923c',dot:'#fb923c'},
  low:{color:'#fbbf24',dot:'#fbbf24'},
  safe:{color:'#4ade80',dot:'#4ade80'}
};

const ATTACK_CARDS=[
  {title:'Credential Harvesting',desc:'Steals login passwords & usernames',color:'#f43f5e'},
  {title:'CEO Fraud / BEC',desc:'Impersonates executives for wire transfers',color:'#fb923c'},
  {title:'Fake Invoice Scam',desc:'Fraudulent billing & payment requests',color:'#fb923c'},
  {title:'Banking Scam',desc:'Targets OTPs and banking credentials',color:'#f43f5e'},
  {title:'Package Delivery',desc:'Fake delivery fees to steal card data',color:'#fbbf24'},
  {title:'Crypto Scam',desc:'Steals wallet seeds & crypto transfers',color:'#f43f5e'},
  {title:'Romance Scam',desc:'Emotional manipulation for money',color:'#ec4899'},
  {title:'Job Offer Scam',desc:'Upfront fees & identity document theft',color:'#fb923c'},
  {title:'Tech Support Scam',desc:'Remote access & fake repair fees',color:'#fb923c'},
  {title:'WhatsApp Scam',desc:'Chain messages & fake free offers',color:'#25d366'},
  {title:'Instagram DM Scam',desc:'Fake collabs & copyright threats',color:'#ec4899'},
  {title:'SMS Phishing',desc:'OTP theft via fake bank/delivery SMS',color:'#fb923c'}
];
